### ISSUE TITLE
fixes related to 0.14 and oidc client

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-oidc-provider-plugin#3]
While testing https://github.com/learningequality/kolibri-oidc-provider-plugin/pull/1 we observed new bahavior in 0.14 related to an infinite redirect loop.

Let's make the fixes necessary to get the flows working agin

**Comment by jredrejo** [comment]
It was a problem with the kolibri oidc client plugin and has been solved in that package

**Comment by indirectlylit** [comment]
great! mind linking to the change here?

**Comment by jredrejo** [comment]
> great! mind linking to the change here?

Sure, it was this commit https://github.com/learningequality/kolibri-oidc-client-plugin/commit/ac5aef346bbed3be045630c9b4c4a666c48d611a

The problem was that, previously, after [this comment,](https://github.com/learningequality/kolibri-oidc-client-plugin/pull/4#discussion_r385920524) `configs.get `was used, setting the default value instead of using `OR`, but when an empty string is returned, the default value is not set. It's only used when `None` is returned, so the redirect to `OIDC_OP_AUTHORIZATION_ENDPOINT` was being to itself ( `'' `) instead of to `/authorize`
